### ISSUE TITLE
run code not on matlab

### ISSUE THREAD

**Issue by Avaneesh-S** [kshmelkov/incremental_detectors#16]
is there a way we can run this code not on matlab and instead on Google colab since there are many who are not used to matlab and colab is more easier and preferred (like me) .

**Comment by kshmelkov** [comment]
You can try to find another implementation of edgeboxes or use completely different proposals that don't require matlab.

Looks like opencv_contrib has edgeboxes now, but I haven't tested them
https://github.com/opencv/opencv_contrib/blob/96ea9a0d8a2dee4ec97ebdec8f79f3c8a24de3b0/modules/ximgproc/samples/edgeboxes_demo.py

**Comment by Avaneesh-S** [comment]
Thank You .
Quick follow up : can you recommend any material to learn how to implement the method on other object detectors , i am trying to do it with SSD_MOBILENET_V2 trained on COCO 2017. I find no available online related to how to implement this, or getting started with it
